---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - java
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.java"
exclude_paths:
- config/
- resources/static/
